[[users]]
username = "tangyuanjc"
role = "owner"

[[users]]
username = "AndrewYNg"
role = "kol"

[[users]]
username = "sama"
role = "kol"

[[users]]
username = "ylecun"
role = "kol"

[[users]]
username = "karpathy"
role = "kol"

[[users]]
username = "swyx"
role = "kol"

[[users]]
username = "simonw"
role = "kol"

[[users]]
username = "alexalbert__"
role = "kol"

[[users]]
username = "jerryjliu0"
role = "kol"

[[users]]
username = "lmsysorg"
role = "kol"

[[users]]
username = "OpenAIDevs"
role = "kol"

[[users]]
username = "op7418"
role = "kol"

[[users]]
username = "dotey"
role = "kol"
